server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat

redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 0
  # redis服务器地址（默认为loaclhost）
  host: 127.0.0.1
  # redis端口（默认为6379）
  port: 6379
  # redis访问密码（默认为空）
  password:
  # redis连接超时时间（单位毫秒）
  timeout: 5000
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1

mybatis:
  mapper-locations: classpath:com.gwo.myblog.mapper/*.xml
  type-aliases-package: com.gwo.myblog.mapper
